### ISSUE TITLE
Make the code async

### ISSUE THREAD

**Issue by omid** [pouriya/sssh#16]
Sure all file reads can be async

**Comment by pouriya** [comment]
* Why? What's the benefits of this change?
* If we are going to do that? Can we do it in a way that the executable size will be the same?

**Comment by omid** [comment]
Not a biggy.
Just to not block the thread, as you know.
Since we expect the files to be very small to read and write, so it's not important at all.

I'm kinda sure the file size will be increased. Since you need a runtime (most probably tokio) at least!
If size is important, then I'll create some other tickets :D

**Comment by pouriya** [comment]
I will append the following to `Cargo.toml`:
```toml
[profile.release]
opt-level = 'z'     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = 'abort'     # Abort on panic
strip = true
```
It reduces the size from **6.5**MB to **1.3**MB for `x86_64-unknown-linux-gnu` target.

Is there anything else I can do?

**Comment by omid** [comment]
Nope, they are perfect.
There are some other stuff, but mostly may not worth it!
(for example, compile in no-std)
